[workspace]
members = [
        "zebrad",
        "zebra-chain",
        "zebra-network",
        "zebra-state",
        "zebra-script",
        "zebra-consensus",
        "zebra-rpc",
        "zebra-client",
        "zebra-node-services",
        "zebra-test",
        "zebra-utils",
        "tower-batch",
        "tower-fallback",
]

[profile.dev]
panic = "abort"

# Speed up tests by optimizing performance-critical crates

[profile.dev.package.blake2b_simd]
opt-level = 3

[profile.dev.package.ff]
opt-level = 3

[profile.dev.package.group]
opt-level = 3

[profile.dev.package.pasta_curves]
opt-level = 3

[profile.dev.package.halo2_proofs]
opt-level = 3

[profile.dev.package.halo2_gadgets]
opt-level = 3

[profile.dev.package.bls12_381]
opt-level = 3

[profile.dev.package.minreq]
opt-level = 1

[profile.dev.package.zcash_proofs]
opt-level = 1


[profile.release]
panic = "abort"

[patch.crates-io]

# TODO: replace with upstream librustzcash when these changes are merged (#3037)
#       remove these after a new librustzcash release (#2982)

# These are librustzcash file requirements specified in its workspace Cargo.toml,
# that we must replace with git requirements
equihash = { git = "https://github.com/zcash/librustzcash.git", rev = "9c1ed86c5aa8ae3b6d6dcc1478f2d6ba1264488f" }
hdwallet = { git = "https://github.com/nuttycom/hdwallet", rev = "576683b9f2865f1118c309017ff36e01f84420c9" }
zcash_encoding = { git = "https://github.com/zcash/librustzcash.git", rev = "9c1ed86c5aa8ae3b6d6dcc1478f2d6ba1264488f" }
zcash_note_encryption = { git = "https://github.com/zcash/librustzcash.git", rev = "9c1ed86c5aa8ae3b6d6dcc1478f2d6ba1264488f" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "9c1ed86c5aa8ae3b6d6dcc1478f2d6ba1264488f" }
# Currently pointing to `download-sprout-params-new` branch which contains the
# changes from `download-sprout-params-new` rebased on top of 9c1ed86c as
# required by `zcash/Cargo.toml`.
zcash_proofs = { git = "https://github.com/ZcashFoundation/librustzcash.git", rev = "5761bb4b731a739ce7d156e3a586f282e9fe0eaf" }
